###
GET http://graddoor/?mode=DB&cmsAction=testAction

###
POST http://graddoor/
Content-Type: application/json

mode=DB&cmsAction=loadTable&tableName=fasdwe&columnsParam={"a":23}


### Send POST request with json body
POST http://graddoor/
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}


### Send POST request with json body
POST http://graddoor/
Content-Type: application/x-www-form-urlencoded

mode=DB&cmsAction=loadTable&tableName=c_00_margin.csv&columnsParam=["id","value"]

### Send POST request with json body
POST http://graddoor/
Content-Type: application/x-www-form-urlencoded

mode=DB&cmsAction=loadTable&tableName=c_00_margin.csv&columnsParam={"id":"id","value":"value"}
